### ISSUE TITLE
Additional labels to add

### ISSUE THREAD

**Issue by JDutil** [spree/spreebot#18]
Few other useful actions that I'll add if @peterberkenbosch doesn't get to it first:

- [x] address_feedback - close issue and message requests feedback be addressed
- [x] need_specs - close issue and message requests specs
- [x] discussion - close issue and message request people to discuss on spree-user mailing list

**Comment by peterberkenbosch** [comment]
@JDutil @BDQ need to review the wording in the explanations in 2864a5d then it's good to go.

**Comment by peterberkenbosch** [comment]
reject:address_feedback
